[Setup]
AppName=Mini Compress
AppVersion=1.0
DefaultDirName={autopf}\MiniCompress
DefaultGroupName=Mini Compress
PrivilegesRequired=lowest
OutputBaseFilename=MiniCompress
Compression=lzma2/ultra64
SolidCompression=yes
SetupIconFile=logo.ico

[Files]
Source: "compress.ps1";          DestDir: "{app}"
Source: "compress-hidden.vbs";   DestDir: "{app}"
Source: "ffmpeg.exe";           DestDir: "{app}"
Source: "pngquant.exe";           DestDir: "{app}"
Source: "logo.ico"; DestDir: "{app}"

[Registry]
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Compress"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile\shell\lossless"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Lossless"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile\shell\lossless\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" lossless ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile\shell\q90"; ValueType: string; ValueName: "MUIVerb"; ValueData: "90% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile\shell\q90\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 90 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile\shell\q75"; ValueType: string; ValueName: "MUIVerb"; ValueData: "75% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile\shell\q75\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 75 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile\shell\q50"; ValueType: string; ValueName: "MUIVerb"; ValueData: "50% Quality"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4v\shell\CompressFile\shell\q50\command"; ValueType: string; ValueData: "wscript.exe ""{app}\compress-hidden.vbs"" 50 ""%1"" ""{app}"""