[Setup]
AppName=Mini Convert
AppVersion=1.0
DefaultDirName={autopf}\MiniConvert
DefaultGroupName=Mini Convert
PrivilegesRequired=lowest
OutputBaseFilename=MiniConvert
Compression=lzma2/ultra64
SolidCompression=yes
SetupIconFile=logo.ico

[Files]
Source: "convert.ps1";          DestDir: "{app}"
Source: "convert-hidden.vbs";   DestDir: "{app}"
Source: "ffmpeg.exe";           DestDir: "{app}"
Source: "logo.ico"; DestDir: "{app}"

[Registry]
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\jpg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to JPG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\jpg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" jpg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\png"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to PNG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\png\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" png ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\webp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\webp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\bmp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to BMP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\bmp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" bmp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\tiff"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to TIFF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\tiff\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" tiff ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\avif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\avif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\ico"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to ICO"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpg\shell\ConvertImage\shell\ico\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ico ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\jpg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to JPG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\jpg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" jpg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\png"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to PNG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\png\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" png ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\webp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\webp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\bmp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to BMP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\bmp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" bmp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\tiff"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to TIFF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\tiff\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" tiff ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\avif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\avif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\ico"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to ICO"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.jpeg\shell\ConvertImage\shell\ico\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ico ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\jpg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to JPG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\jpg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" jpg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\png"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to PNG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\png\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" png ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\webp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\webp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\bmp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to BMP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\bmp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" bmp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\tiff"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to TIFF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\tiff\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" tiff ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\avif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\avif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\ico"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to ICO"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.png\shell\ConvertImage\shell\ico\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ico ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\jpg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to JPG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\jpg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" jpg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\png"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to PNG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\png\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" png ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\webp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\webp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\bmp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to BMP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\bmp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" bmp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\tiff"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to TIFF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\tiff\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" tiff ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\avif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\avif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\ico"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to ICO"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.bmp\shell\ConvertImage\shell\ico\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ico ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\jpg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to JPG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\jpg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" jpg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\png"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to PNG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\png\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" png ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\webp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\webp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\bmp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to BMP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\bmp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" bmp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\tiff"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to TIFF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\tiff\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" tiff ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\avif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\avif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\ico"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to ICO"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webp\shell\ConvertImage\shell\ico\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ico ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\jpg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to JPG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\jpg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" jpg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\png"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to PNG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\png\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" png ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\webp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\webp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\bmp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to BMP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\bmp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" bmp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\tiff"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to TIFF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\tiff\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" tiff ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\avif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\avif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\ico"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to ICO"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.tiff\shell\ConvertImage\shell\ico\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ico ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\jpg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to JPG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\jpg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" jpg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\png"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to PNG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\png\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" png ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\webp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\webp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\bmp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to BMP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\bmp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" bmp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\tiff"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to TIFF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\tiff\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" tiff ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\avif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\avif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\ico"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to ICO"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avif\shell\ConvertImage\shell\ico\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ico ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\jpg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to JPG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\jpg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" jpg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\png"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to PNG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\png\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" png ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\webp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\webp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\bmp"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to BMP"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\bmp\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" bmp ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\tiff"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to TIFF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\tiff\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" tiff ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\avif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\avif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\ico"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to ICO"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ico\shell\ConvertImage\shell\ico\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ico ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp3\shell\ConvertAudio\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.wav\shell\ConvertAudio\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flac\shell\ConvertAudio\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.aac\shell\ConvertAudio\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.ogg\shell\ConvertAudio\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.m4a\shell\ConvertAudio\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\mp4"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP4"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\mp4\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp4 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\mkv"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MKV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\mkv\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mkv ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\avi"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVI"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\avi\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avi ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\mov"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MOV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\mov\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mov ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\webm"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBM"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\webm\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webm ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\gif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to GIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\gif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" gif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mp4\shell\ConvertVideo\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\mp4"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP4"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\mp4\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp4 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\mkv"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MKV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\mkv\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mkv ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\avi"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVI"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\avi\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avi ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\mov"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MOV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\mov\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mov ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\webm"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBM"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\webm\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webm ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\gif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to GIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\gif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" gif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mkv\shell\ConvertVideo\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\mp4"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP4"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\mp4\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp4 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\mkv"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MKV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\mkv\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mkv ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\avi"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVI"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\avi\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avi ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\mov"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MOV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\mov\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mov ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\webm"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBM"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\webm\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webm ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\gif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to GIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\gif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" gif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.avi\shell\ConvertVideo\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\mp4"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP4"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\mp4\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp4 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\mkv"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MKV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\mkv\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mkv ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\avi"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVI"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\avi\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avi ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\mov"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MOV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\mov\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mov ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\webm"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBM"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\webm\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webm ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\gif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to GIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\gif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" gif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.mov\shell\ConvertVideo\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\mp4"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP4"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\mp4\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp4 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\mkv"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MKV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\mkv\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mkv ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\avi"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVI"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\avi\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avi ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\mov"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MOV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\mov\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mov ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\webm"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBM"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\webm\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webm ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\gif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to GIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\gif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" gif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.webm\shell\ConvertVideo\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\mp4"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP4"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\mp4\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp4 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\mkv"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MKV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\mkv\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mkv ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\avi"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVI"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\avi\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avi ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\mov"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MOV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\mov\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mov ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\webm"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBM"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\webm\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webm ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\gif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to GIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\gif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" gif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.flv\shell\ConvertVideo\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo"; ValueType: string; ValueName: "MUIVerb"; ValueData: "Convert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo"; ValueType: string; ValueName: "SubCommands"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\mp4"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP4"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\mp4\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp4 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\mkv"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MKV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\mkv\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mkv ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\avi"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AVI"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\avi\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" avi ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\mov"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MOV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\mov\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mov ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\webm"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WEBM"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\webm\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" webm ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\gif"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to GIF"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\gif\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" gif ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\mp3"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to MP3"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\mp3\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" mp3 ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\wav"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to WAV"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\wav\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" wav ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\flac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to FLAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\flac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" flac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\aac"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to AAC"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\aac\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" aac ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\ogg"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to OGG"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\ogg\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" ogg ""%1"" ""{app}"""
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\m4a"; ValueType: string; ValueName: "MUIVerb"; ValueData: "to M4A"
Root: HKCU; Subkey: "Software\Classes\SystemFileAssociations\.gif\shell\ConvertVideo\shell\m4a\command"; ValueType: string; ValueData: "wscript.exe ""{app}\convert-hidden.vbs"" m4a ""%1"" ""{app}"""